name: Pull Request Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with flake8
        run: |
          flake8 src/jsonlogic --count --show-source --statistics --max-line-length=120


      - name: MyPy
        run: |
          mypy src/jsonlogic --ignore-missing-imports


      - name: Pytest
        run: |
          coverage run --source jsonlogic/ -m pytest && coverage report -m --fail-under 95
